# Generated by Django 5.2.4 on 2025-08-05 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0002_userfollowing_user_following"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollowing",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="userfollowing",
            unique_together={("to_user", "from_user")},
        ),
    ]
