# Generated by Django 5.2.4 on 2025-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed_image",
            field=models.ImageField(blank=True, null=True, upload_to="todo/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="todo/default.jpg",
                null=True,
                upload_to="todo/%Y/%m/%d/thumbnail",
            ),
        ),
    ]
