# Generated by Django 5.2.4 on 2025-07-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("free", "자유"),
                            ("travel", "여행"),
                            ("cat", "고양이"),
                            ("dog", "개"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                ("content", models.TextField(verbose_name="본문")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일자"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
            ],
        ),
    ]
