# Generated by Django 5.2.4 on 2025-07-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_options_blog_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("free", "자유"),
                    ("travel", "여행"),
                    ("cat", "고양이"),
                    ("dog", "개"),
                ],
                default="free",
                max_length=20,
                verbose_name="카테고리",
            ),
        ),
    ]
