# Generated by Django 5.2.4 on 2025-07-30 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-create_at", "-id"),
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글 목록",
            },
        ),
    ]
